# Generated by Django 5.1.7 on 2025-05-28 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeApp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Иван', max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(default='Иванов', max_length=20, verbose_name='Имя')),
                ('phone', models.CharField(default='+7 999 999 99 99', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(default='example@gmail.com', help_text='Обязательно для заполнения', max_length=20, verbose_name='Адрес эл. почты')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата отправки данных')),
                ('contact', models.CharField(choices=[('email', 'Электронная почта'), ('phone', 'Телефон'), ('messenger', 'Мессенджер'), ('socials', 'Социальные сети')], default='email', max_length=255, verbose_name='Предпочитаемый способ взаимодействия')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', max_length=255, verbose_name='Нравятся ли вам фильмы Studio Ghibli?')),
                ('number_of_movies', models.PositiveIntegerField(default='0', verbose_name='Как много фильмов Studio Ghibli вы смотрели?')),
                ('characters', models.CharField(choices=[('Totoro', 'Тоторо'), ('Chihiro', 'Тихиро Огино'), ('NoFace', 'Безликий'), ('Princess Mononoke', 'Сан (Принцесса Мононоке)'), ('Howl', 'Хаул')], default='Totoro', max_length=255, verbose_name='Какие из перечисленных персонажей вам больше всего нравятся?')),
                ('fav_producer', models.CharField(choices=[('Хаяо Миядзаки', 'Хаяо Миядзаки'), ('Хироюки Морита', 'Хироюки Морита'), ('Хиромаса Ёнэбаяси', 'Хиромаса Ёнэбаяси'), ('Томоми Мотидзуки', 'Томоми Мотидзуки'), ('Михаэль Дюдок де Вит', 'Михаэль Дюдок де Вит'), ('Исао Такахата', 'Исао Такахата'), ('Ёсифуми Кондо', 'Ёсифуми Кондо'), ('Горо Миядзаки', 'Горо Миядзаки')], default='Хаяо Миядзаки', max_length=255, verbose_name='Фильмы какого режиссера вы предпочитаете?')),
                ('films', models.CharField(choices=[('film1', '«Унесенные призраками»'), ('film2', '«Мой сосед Тоторо»'), ('film3', '«Небесный замок Лапута»'), ('film4', '«Ведьмина служба доставки»'), ('film5', '«Шепот сердца»'), ('film6', '«Принцесса Мононоке»'), ('film7', '«Ходячий замок»'), ('film8', '«Рыбка Поньо на утесе»'), ('film9', '«Со склонов Кокурико»'), ('film10', '«Ветер крепчает»')], default='film1', max_length=255, verbose_name='Какой из представленных фильмов по вашему мнению является лучшим?')),
                ('fav_film', models.TextField(verbose_name='Какой ваш любимый фильм студии?')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeApp1.personal_info', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опрос',
                'ordering': ('-pk',),
            },
        ),
    ]
