# Generated by Django 5.1.7 on 2025-05-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeApp1', '0002_personal_info_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fav_film',
            field=models.TextField(verbose_name='Какой ваш любимый фильм студии и почему?'),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки данных'),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='surname',
            field=models.CharField(default='Иванов', max_length=20, verbose_name='Фамилия'),
        ),
    ]
